In [1]:
import numpy as np
import pandas as pd
from sklearn.metrics.pairwise import cosine_similarity
from numpy import dot
from numpy.linalg import norm

In [2]:
df=pd.read_csv('dataset.csv')

In [3]:
worldcoin=pd.read_csv('worldcoin.csv')

In [4]:
worldcoin.head()

              HOUR :: DATE  AVG(PRICE)
0  2023-07-24 00:00:00.000    2.357397
1  2023-07-25 00:00:00.000    2.138324
2  2023-07-26 00:00:00.000    2.337500
3  2023-07-27 00:00:00.000    2.195000
4  2023-07-28 00:00:00.000    2.158333

In [5]:
worldcoin.shape

(210, 2)

In [6]:
worldcoin.shape

(210, 2)

In [7]:
df.shape

(72946, 10)

In [8]:
df.head()

,Unnamed: 0,open,high,low,close,volume,marketCap,timestamp,crypto_name,date
0,0,112.900002,118.800003,107.142998,115.910004,0.0,1.288693e+09,2013-05-05T23:59:59.999Z,Bitcoin,2013-05-05
1,1,3.493130,3.692460,3.346060,3.590890,0.0,6.229819e+07,2013-05-05T23:59:59.999Z,Litecoin,2013-05-05
2,2,115.980003,124.663002,106.639999,112.300003,0.0,1.249023e+09,2013-05-06T23:59:59.999Z,Bitcoin,2013-05-06
3,3,3.594220,3.781020,3.116020,3.371250,0.0,5.859436e+07,2013-05-06T23:59:59.999Z,Litecoin,2013-05-06
4,4,112.250000,113.444000,97.699997,111.500000,0.0,1.240594e+09,2013-05-07T23:59:59.999Z,Bitcoin,2013-05-07

In [9]:
unique_coins=df['crypto_name'].unique()

In [10]:
unique_coins.size

56

In [11]:
wcvecto=(worldcoin['AVG(PRICE)']).values
wcvector=wcvecto.reshape(-1,1)
print(wcvector)

[[2.35739732]
 [2.13832415]
 [2.3375    ]
 [2.195     ]
 [2.15833333]
 [2.29865818]
 [2.35138165]
 [2.3025    ]
 [2.32916667]
 [2.3975    ]
 [2.31166667]
 [2.255     ]
 [2.13083333]
 [2.07208333]
 [2.04541667]
 [1.94375   ]
 [1.90416667]
 [1.75958333]
 [1.71      ]
 [1.75666667]
 [1.79916667]
 [1.78916667]
 [1.72666667]
 [1.57458333]
 [1.48291667]
 [1.46916667]
 [1.47916667]
 [1.49208333]
 [1.47291667]
 [1.45291667]
 [1.39041667]
 [1.42541667]
 [1.31416667]
 [1.26291667]
 [1.29166667]
 [1.24041667]
 [1.21      ]
 [1.26041667]
 [1.18333333]
 [1.11875   ]
 [1.15291667]
 [1.12541667]
 [1.10795833]
 [1.05541667]
 [1.157375  ]
 [1.2625    ]
 [1.16125   ]
 [1.14791667]
 [1.09933333]
 [1.055     ]
 [1.01679117]
 [1.01406046]
 [1.03170833]
 [1.156875  ]
 [1.50083333]
 [1.33791667]
 [1.33666667]
 [1.365     ]
 [1.45291667]
 [1.47875   ]
 [1.57208333]
 [1.56125   ]
 [1.575     ]
 [1.67875   ]
 [1.69541667]
 [1.72875   ]
 [1.825     ]
 [1.76708333]
 [1.75208333]
 [1.70791667]
 [1.69833333]
 [1.62416667]
 [1.52166667]
 [1.545     ]
 [1.57875   ]
 [1.63416667]
 [1.59666667]
 [1.55208333]
 [1.53708333]
 [1.58125   ]
 [1.51208333]
 [1.47125   ]
 [1.48583333]
 [1.50625   ]
 [1.57708333]
 [1.62875   ]
 [1.57291667]
 [1.46125   ]
 [1.5175    ]
 [1.55      ]
 [1.62291667]
 [1.56708333]
 [1.67625   ]
 [1.73291667]
 [1.78166667]
 [1.82958333]
 [1.87875   ]
 [1.83375   ]
 [1.86833333]
 [1.9675    ]
 [1.92833333]
 [1.82708333]
 [1.80376091]
 [1.87083333]
 [1.85      ]
 [1.80708333]
 [1.80458333]
 [1.81875   ]
 [1.81458333]
 [1.75875   ]
 [1.98791667]
 [1.92666667]
 [2.17375   ]
 [2.22125   ]
 [2.36416667]
 [2.31625   ]
 [2.06583333]
 [1.95875   ]
 [2.33875   ]
 [2.33916667]
 [2.34833333]
 [2.47375   ]
 [2.41583333]
 [2.47375   ]
 [2.68375   ]
 [2.68041667]
 [2.57      ]
 [2.47541667]
 [2.50916667]
 [2.39166667]
 [2.43875   ]
 [2.46625   ]
 [2.49875   ]
 [2.46208333]
 [2.44166667]
 [2.46708333]
 [2.44083333]
 [2.48625   ]
 [2.50333333]
 [2.62291667]
 [2.49166667]
 [2.43125   ]
 [2.4175    ]
 [2.57333333]
 [2.6025    ]
 [3.11791667]
 [4.1525    ]
 [3.965     ]
 [3.95833333]
 [3.5775    ]
 [3.61924569]
 [3.60951312]
 [3.42335735]
 [3.44192427]
 [3.59090853]
 [3.74507405]
 [3.60833333]
 [3.52458333]
 [3.5325    ]
 [3.65583333]
 [3.72166667]
 [3.58583333]
 [3.68666667]
 [3.42666667]
 [3.13916667]
 [3.02146008]
 [2.81242384]
 [2.76083333]
 [2.66833333]
 [2.65875   ]
 [2.53942009]
 [2.78083333]
 [2.87541667]
 [2.83778867]
 [2.81724896]
 [2.75849063]
 [2.775     ]
 [2.72916667]
 [2.66941933]
 [2.52142199]
 [2.49208333]
 [2.5425    ]
 [2.385     ]
 [2.21791667]
 [2.23666667]
 [2.27375   ]
 [2.31458333]
 [2.39791667]
 [2.36      ]
 [2.3375    ]
 [2.47166667]
 [2.38375   ]
 [2.26958333]
 [2.32083333]
 [2.33791667]
 [2.24583333]
 [2.20565085]
 [2.22666667]
 [2.28541667]
 [2.37541667]
 [2.44458333]
 [2.51291667]
 [2.51416667]
 [2.56375   ]
 [2.70916667]
 [2.92791667]
 [3.18041667]
 [4.05958333]
 [4.41634562]
 [       nan]]

In [27]:
capture=[]

wcvector=(worldcoin['AVG(PRICE)']).values[:-1]



for coin in unique_coins:
    coin_data=df[df['crypto_name']==coin]
    coin_data.dropna( axis=0,  subset=None, inplace=False, ignore_index=False)
    if (coin_data['close'].size)<worldcoin['AVG(PRICE)'].size:
        continue
    for i in range (worldcoin['AVG(PRICE)'].size,coin_data['close'].size):
        df1=coin_data.iloc[i-worldcoin['AVG(PRICE)'].size:i]
        
        coinvector=(df1['close']).values[:-1]
        
        
        
        
        similarty=dot(wcvector,coinvector)/(norm(wcvector)*norm(coinvector))
        if(similarty>0.98):
            capture.append([coin,df1['date'].iloc[0]])

            
print(capture)

[['Bitcoin', '2015-07-07'], ['Bitcoin', '2015-07-08'], ['Bitcoin', '2015-07-09'], ['Bitcoin', '2015-07-10'], ['Bitcoin', '2015-07-11'], ['Bitcoin', '2015-07-12'], ['Bitcoin', '2015-07-13'], ['Bitcoin', '2015-07-14'], ['Bitcoin', '2015-07-15'], ['Bitcoin', '2015-07-16'], ['Bitcoin', '2015-07-17'], ['Bitcoin', '2015-07-18'], ['Bitcoin', '2015-07-19'], ['Bitcoin', '2015-07-20'], ['Bitcoin', '2015-07-21'], ['Bitcoin', '2015-07-22'], ['Bitcoin', '2015-07-23'], ['Bitcoin', '2015-07-24'], ['Bitcoin', '2015-07-25'], ['Bitcoin', '2015-07-26'], ['Bitcoin', '2015-07-27'], ['Bitcoin', '2015-07-28'], ['Bitcoin', '2015-07-29'], ['Bitcoin', '2015-07-30'], ['Bitcoin', '2015-07-31'], ['Bitcoin', '2015-08-01'], ['Bitcoin', '2015-08-02'], ['Bitcoin', '2015-08-03'], ['Bitcoin', '2015-08-04'], ['Bitcoin', '2015-08-05'], ['Bitcoin', '2021-04-29'], ['Bitcoin', '2021-04-30'], ['Bitcoin', '2021-05-01'], ['Bitcoin', '2021-05-02'], ['Bitcoin', '2021-05-03'], ['Bitcoin', '2021-05-04'], ['Dogecoin', '2015-09-03'], ['Monero', '2019-01-12'], ['Monero', '2019-01-13'], ['Monero', '2019-01-14'], ['Monero', '2019-01-15'], ['Monero', '2019-01-16'], ['Monero', '2019-01-17'], ['Ethereum Classic', '2018-12-30'], ['Ethereum Classic', '2018-12-31'], ['Ethereum Classic', '2019-01-01'], ['Ethereum Classic', '2019-01-02'], ['Ethereum Classic', '2019-01-03'], ['Ethereum Classic', '2019-01-04'], ['Ethereum Classic', '2019-01-05'], ['Maker', '2018-10-20'], ['Maker', '2018-10-21'], ['Maker', '2018-10-22'], ['Maker', '2018-10-23'], ['Maker', '2018-10-24'], ['Maker', '2018-10-25'], ['Maker', '2018-10-26'], ['Maker', '2018-10-27'], ['Maker', '2018-10-28'], ['Maker', '2018-10-29'], ['Maker', '2018-10-30'], ['Maker', '2018-10-31'], ['Maker', '2018-11-01'], ['Maker', '2018-11-02'], ['Maker', '2018-11-03'], ['TRON', '2020-03-31'], ['TRON', '2020-04-01'], ['TRON', '2020-04-02'], ['TRON', '2020-04-03'], ['TRON', '2020-04-04'], ['TRON', '2020-04-05'], ['TRON', '2020-04-06'], ['TRON', '2020-04-07'], ['Cardano', '2018-11-03'], ['Cardano', '2018-11-04'], ['Cardano', '2018-11-05'], ['Cardano', '2018-11-06'], ['Cardano', '2018-11-07'], ['Cardano', '2018-11-08'], ['Cardano', '2018-11-09'], ['Quant', '2020-06-08'], ['Quant', '2020-06-09'], ['Quant', '2020-06-10'], ['Quant', '2020-06-11'], ['Quant', '2020-06-12'], ['Quant', '2020-06-13'], ['Cronos', '2019-09-04'], ['Cronos', '2019-09-05'], ['Cronos', '2019-09-06'], ['Cronos', '2019-09-07'], ['Cronos', '2019-09-08'], ['Cronos', '2019-09-09'], ['Cronos', '2019-09-10'], ['Cronos', '2019-09-11'], ['Cronos', '2019-09-12'], ['Cronos', '2019-09-13'], ['Cronos', '2019-09-14'], ['Cronos', '2019-09-15'], ['Cronos', '2019-09-16'], ['Cronos', '2019-09-17'], ['Cronos', '2019-09-18'], ['Wrapped Bitcoin', '2021-04-29'], ['Wrapped Bitcoin', '2021-04-30'], ['Wrapped Bitcoin', '2021-05-01'], ['Wrapped Bitcoin', '2021-05-02'], ['Wrapped Bitcoin', '2021-05-03'], ['Wrapped Bitcoin', '2021-05-04'], ['UNUS SED LEO', '2020-11-26'], ['UNUS SED LEO', '2020-11-27'], ['UNUS SED LEO', '2020-11-29'], ['UNUS SED LEO', '2020-11-30'], ['UNUS SED LEO', '2020-12-01'], ['UNUS SED LEO', '2020-12-02'], ['UNUS SED LEO', '2020-12-03'], ['UNUS SED LEO', '2020-12-04'], ['UNUS SED LEO', '2020-12-05'], ['UNUS SED LEO', '2020-12-06'], ['UNUS SED LEO', '2021-08-28'], ['UNUS SED LEO', '2021-08-29'], ['UNUS SED LEO', '2021-08-30'], ['UNUS SED LEO', '2021-08-31'], ['UNUS SED LEO', '2021-09-01'], ['UNUS SED LEO', '2021-09-02'], ['UNUS SED LEO', '2021-09-03'], ['UNUS SED LEO', '2021-09-04'], ['UNUS SED LEO', '2021-09-05'], ['UNUS SED LEO', '2021-09-06'], ['UNUS SED LEO', '2021-09-08'], ['UNUS SED LEO', '2021-09-09'], ['Algorand', '2021-04-30'], ['Algorand', '2021-05-01'], ['Algorand', '2021-05-02'], ['Algorand', '2021-05-03'], ['Algorand', '2021-05-04'], ['Algorand', '2021-05-05'], ['FTX Token', '2019-09-11'], ['FTX Token', '2019-09-12'], ['Hedera', '2021-04-29'], ['Hedera', '2021-04-30'], ['Hedera', '2021-05-01'], ['Hedera', '2021-05-02'], ['Hedera', '2021-05-03'], ['Hedera', '2021-05-04'], ['Hedera', '2021-05-05'], ['Hedera', '2021-05-06']]